services:
  db:
    image: postgres:latest
    container_name: task_manager
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U '${POSTGRES_USERNAME}' -d '${POSTGRES_DATABASE}'"]
      interval: 5s
      retries: 5
      timeout: 3s
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
